### ISSUE TITLE
メッセージの実装①（店舗・スタジオ登録時）

### ISSUE THREAD

**Issue by ecoyamas** [ecoyamas/msrs_app#12]
【作業内容】
・メッセージを表示させたい箇所の洗い出し。
・flash messageを実装

・店舗登録時に店舗を追加しましたのメッセージ表示
・店舗削除時に店舗を削除しましたのメッセージ表示
・スタジオ登録時に店舗を追加しましたのメッセージ表示
・スタジオ削除時に店舗を削除しましたのメッセージ表示

**Comment by fumimi** [comment]
done
