### ISSUE TITLE
【予約新規作成画面】予約新規作成画面 修正

### ISSUE THREAD

**Issue by ecoyamas** [ecoyamas/msrs_app#72]
【作業内容】
・スタジオ詳細画面の「予約フォームへ」のボタンの文字列を「予約フォーム」
・スタジオ詳細画面から予約新規作成画面へのリンク実装。
・h1タグに店舗名を表示。
・スタジオ欄のプルダウンにスタジオ名が選択されている状態で予約新規作成画面を表示。
・予約新規作成画面の「予約状況」リンクを押下するとスタジオ詳細画面に遷移。

**Comment by fumimi** [comment]
done
